.github/pull_request_template.md
=> [CHORE] pull request template 추가

.gitmodules, README.md
- idl 서브모듈 추가
- readme 파일 업데이트
=> [CHORE] IDL submodule 추가 및 Readme 업데이트

.github/workflows/branch.yaml, bin/deploy.sh, docker-compose.yml
- CD 파이프라인 구성합니다
- main 브랜치에 push 가 일어나면 ci 를 돌리고 배포까지 합니다
=> [CHORE] GCP Compute Engine 으로 CD 파이프라인 구성

.github/workflows/branch.yaml
=> [FIX] CD 스크립트 수정

.github/workflows/branch.yaml
- 이걸로 no such directory 문제 해결 되거나 디버그용 로깅 남기기
=> [FIX] CD 스크립트 고치기 2

.github/workflows/branch.yaml
- ssh user 가 runner 로 되면서 no such directory 가 떴던 것
- user secret 추가하여 고칩니다
=> [FIX] CD 스크립트 고치기 3

src/converter/user.converter.go, src/handler/user.handler.go, src/model/error.go, src/router/router.go, src/service/user.service.go
- DeleteUser의 Handler 및 Service 구현
- UpdateUser의 Handler 및 Service 구현
- 모델과 proto간 disorder_type 변환을 위한 converter 추가
=> [FEAT] User proto 구현 기능 추가

bin/deploy.sh
- reference 하고 있는 submodule 을 가져오도록 수정
=> [CHORE] deploy 스크립트 업데이트하기

src/handler/user.handler.go, src/middleware/error.middleware.go, src/model/error.go, src/router/router.go, src/service/user.service.go
- errorDTO 추가하고 커스텀 handler 추가합니다
=> [FEAT] Error Handler 추가

bin/deploy.sh
=> [Fix] cd 스크립트

ai/server.py, src/handler/feedback.handler.go
=> [FIX] 필드 오타

src/handler/feedback.handler.go
- defer 는 함수의 block 마지막에서 실행시키므로 혹시 file lock 이 잡혀 있을까봐 함수로 뺍니다
- file path 에 "/" 하나가 안들어가 있어서 수정합니다
=> [FIX] extract write file function for concurrency and fix file path

src/handler/feedback.handler.go
- file not exist error 는 잡는데 directory 는 못잡는다고 해서 더 general 한거 사용합니다
=> [FIX] use more general error check

src/constant/shared.go, src/handler/feedback.handler.go
=> [FIX] no dir error

ai/server.py, src/constant/grpc.go, src/handler/feedback.handler.go
=> [FIX] internal proto field name and timeout

ai/server.py
=> [FIX] field name mismatch

config/wire_gen.go, src/handler/sentence.handler.go
=> [Fix] nil pointer

ai/fluentify.py
=> [Fix] shared volume path

ai/README.md, ai/data/pro-data.json, ai/data/prompt.yaml, ai/example.py, ai/fluentify.py
=> [Fix] typo

ai/fluentify.py
- 서버 환경에 띄우면서 경로 설정 같은걸 조금 바꾼게 있었는데 아까 모델 업데이트하면서 무지성 복붙해서 설정이 틀어짐...
=> [Fix] redundant path

src/handler/feedback.handler.go
- negative feedback 이 없을 경우 default 를 내려줌
=> [Feat] add default negative feedback

README.md
- Update readme with overview and architecture of the project
=> [Docs] update readme
